export const projects = [
  {
    id: 1,
    title: '푸드 상세페이지',
    category: '상세페이지 기획 + 디자인',
    coverImage: '/file/page_1.png',
    details: [
      '/file/page_1.png',
      '/file/page_2.gif',
      '/file/page_3.png',
      '/file/page_4.png',
      '/file/page_5.png',
      '/file/page_6.png',
      '/file/page_7.png',
      '/file/page_8.png',
      '/file/page_9.png',
      '/file/page_10.png',
      '/file/page_11.png',
      '/file/page_12.png',
      '/file/page_13.png',
      '/file/page_14.png',
      '/file/page_15.png',
      '/file/page_16.png',
      '/file/page_17.png',
      '/file/page_18.png',
      '/file/page_19.png',
      '/file/page_20.png',
      '/file/page_21.png',
      '/file/page_22.png',
      '/file/page_23.png',
      '/file/page_24.png',
      '/file/page_25.png',
      '/file/page_26.png',
      '/file/page_27.png',
    ],
  },
  {
    id: 2,
    title: '디지털 기기 상세페이지',
    category: '상세페이지 기획 + 디자인',
    coverImage: '/digital/digital_01.png',
    details: [
      '/digital/digital_01.png',
      '/digital/digital_02.png',
      '/digital/digital_03.png',
      '/digital/digital_04.gif',
      '/digital/digital_05.png',
      '/digital/digital_06.png',
      '/digital/digital_07.png',
      '/digital/digital_08.png',
      '/digital/digital_09.png',
      '/digital/digital_10.png',
      '/digital/digital_11.png',
      '/digital/digital_12.png',
      '/digital/digital_13.png',
      '/digital/digital_14.png',
      '/digital/digital_15.png',
      '/digital/digital_16.png',
      '/digital/digital_17.png',
      '/digital/digital_18.png',
      '/digital/digital_19.png',
      '/digital/digital_20.png',
      '/digital/digital_21.png',
      '/digital/digital_22.png',
    ],
  },
  {
    id: 3,
    title: '리빙 상세페이지',
    category: '상세페이지 기획 + 디자인',
    coverImage: '/living/living_1.png',
    details: [
      '/living/living_1.png',
      '/living/living_2.png',
      '/living/living_3.png',
      '/living/living_4.png',
      '/living/living_5.gif',
      '/living/living_6.png',
      '/living/living_7.png',
      '/living/living_8.png',
      '/living/living_9.png',
      '/living/living_10.png',
      '/living/living_11.png',
      '/living/living_12.png',
      '/living/living_13.png',
      '/living/living_14.png',
      '/living/living_15.png',
      '/living/living_16.png',
      '/living/living_17.gif',
      '/living/living_18.png',
      '/living/living_19.png',
      '/living/living_20.png',
      '/living/living_21.png',
      '/living/living_22.png',
      '/living/living_23.png',
      '/living/living_24.png',
      '/living/living_25.png',
      '/living/living_26.png',
    ],
  },
];

export const processSteps = [
  { num: '01', title: '상담 접수', desc: '프로젝트 목표 및 타겟 확인' },
  { num: '02', title: '브랜드 분석', desc: '시장 조사 및 경쟁사 분석' },
  { num: '03', title: '구조 기획안', desc: '전환율 중심의 와이어프레임 설계' },
  { num: '04', title: '디자인 제작', desc: '시각적 매력과 가독성 극대화' },
  { num: '05', title: '수정 및 보완', desc: '피드백 반영 및 디테일 최적화' },
  { num: '06', title: '최종 납품', desc: '완성된 결과물 및 원본 전달' },
];
